image: node:10.15.0

pipelines:
    branches:
        develop:
            - step:
                  name: Automate Testing (develop-branch)
                  caches:
                      - node
                  script:
                      - npm install
                      - jest --updateSnapshot
                      - npm test

        master:
            - step:
                  name: Test and Build (Continuous Integration on Master-branch)
                  caches:
                      - node
                  script:
                      - npm install -g gatsby-cli
                      - npm install
                      - npm test
                      - jest --updateSnapshot
                      - (umask  077 ; echo $ENV_PROD | base64 --decode > .env.production)
                      - gatsby build
                      - rm -rf .env.production
                  artifacts:
                      - public/**

            - step:
                  name: Deploy to Firebase (Production)
                  deployment: production
                  script:
                      - pipe: atlassian/firebase-deploy:0.3.6
                        variables:
                            FIREBASE_TOKEN: $FIREBASE_TOKEN
                            PROJECT_ID: $PROJECT_ID
                            MESSAGE: 'Automate deploying logigos-landing-page by bitbucket-pipeline'
