image: node:10.15.0

pipelines:
    branches:
        master:
            - step:
                  name: Test and Build (Continuous Integration on Master-branch)
                  caches:
                      - node
                  script:
                      - npm install
                      - npm test
                      - npm run build
                  artifacts:
                      - public/**

            - step:
                  name: Deploy to Firebase (Production)
                  deployment: production
                  script:
                      - pipe: atlassian/firebase-deploy:0.3.6
                        variables:
                            FIREBASE_TOKEN: $FIREBASE_TOKEN
                            PROJECT_ID: $PROJECT_ID
                            MESSAGE: 'Automate deploying by bitbucket-pipeline'
