image: node:10.15.0

pipelines:
    branches:
        develop:
            - step:
                  name: Test (Continuous Integration on Develop-branch)
                  caches:
                      - node
                  script:
                      - npm install
                      - npm test
            - step:
                  name: Build (Develop-branch)
                  caches:
                      - node
                  script:
                      - npm install
                      - npm run build
                  artifacts:
                      - public/**
            - step:
                  name: Deploy to Firebase (Production)
                  deployment: production
                  script:
                      - pipe: atlassian/firebase-deploy:0.3.6
                        variables:
                            FIREBASE_TOKEN: $FIREBASE_TOKEN
                            PROJECT_ID: 'myAwesomeProject'
                            MESSAGE: 'Deploying myAwesomeProject'
                            EXTRA_ARGS: '--only functions'
                            DEBUG: 'true'
